/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PageSectionService } from "../pageSection.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PageSectionCreateInput } from "./PageSectionCreateInput";
import { PageSection } from "./PageSection";
import { PageSectionFindManyArgs } from "./PageSectionFindManyArgs";
import { PageSectionWhereUniqueInput } from "./PageSectionWhereUniqueInput";
import { PageSectionUpdateInput } from "./PageSectionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PageSectionControllerBase {
  constructor(
    protected readonly service: PageSectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PageSection })
  @nestAccessControl.UseRoles({
    resource: "PageSection",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPageSection(
    @common.Body() data: PageSectionCreateInput
  ): Promise<PageSection> {
    return await this.service.createPageSection({
      data: {
        ...data,

        page: data.page
          ? {
              connect: data.page,
            }
          : undefined,

        Template: data.Template
          ? {
              connect: data.Template,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        page: {
          select: {
            id: true,
          },
        },

        Template: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PageSection] })
  @ApiNestedQuery(PageSectionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PageSection",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pageSections(@common.Req() request: Request): Promise<PageSection[]> {
    const args = plainToClass(PageSectionFindManyArgs, request.query);
    return this.service.pageSections({
      ...args,
      select: {
        createdAt: true,
        id: true,

        page: {
          select: {
            id: true,
          },
        },

        Template: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PageSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PageSection",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pageSection(
    @common.Param() params: PageSectionWhereUniqueInput
  ): Promise<PageSection | null> {
    const result = await this.service.pageSection({
      where: params,
      select: {
        createdAt: true,
        id: true,

        page: {
          select: {
            id: true,
          },
        },

        Template: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PageSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PageSection",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePageSection(
    @common.Param() params: PageSectionWhereUniqueInput,
    @common.Body() data: PageSectionUpdateInput
  ): Promise<PageSection | null> {
    try {
      return await this.service.updatePageSection({
        where: params,
        data: {
          ...data,

          page: data.page
            ? {
                connect: data.page,
              }
            : undefined,

          Template: data.Template
            ? {
                connect: data.Template,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          page: {
            select: {
              id: true,
            },
          },

          Template: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PageSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PageSection",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePageSection(
    @common.Param() params: PageSectionWhereUniqueInput
  ): Promise<PageSection | null> {
    try {
      return await this.service.deletePageSection({
        where: params,
        select: {
          createdAt: true,
          id: true,

          page: {
            select: {
              id: true,
            },
          },

          Template: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
